version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: eq_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: eq_user
      POSTGRES_PASSWORD: eq_pass
      POSTGRES_DB: eq_test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 